#pragma once
#include "DirectXBase.h"
//#include "ObjectManager.h"
#include "SoundManager.h"
#include "PiplineManager.h"
#include "Joycon.h"
#include "DebugText.h"
#include "RenderTarget.h"
#include "MultiPathFunction.h"